name: publish
on:
  push:
    branches:
    - devel
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: docker build .
    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: docker tag workflow-controller jamhed/workflow-controller:${{ github.ref }}
    - run: docker tag argoexec jamhed/argoexec:${{ github.ref }}
    - run: docker tag argocli  jamhed/argocli:${{ github.ref }}
    - run: docker push jamhed/workflow-controller:${{ github.ref }}
    - run: docker push jamhed/argoexec:${{ github.ref }}
    - run: docker push jamhed/argocli:${{ github.ref }}
